// Resolves foods.mjs into a full food × animal table.
//
//   node scripts/food-data/build.mjs           → writes out/review.json (diff vs current app data)
//   node scripts/food-data/build.mjs --write   → also regenerates src/data/csv-data.ts
//
// Fails loudly on unknown status codes, reasons, sources or any unresolved cell.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

import { ANIMALS, GROUPS, STATUS, SOURCES, R } from './rules.mjs';
import { foods } from './foods.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const csvPath = path.join(root, 'src/data/csv-data.ts');
const Papa = createRequire(import.meta.url)(path.join(root, 'node_modules/papaparse'));

const groupOf = {};
for (const [g, members] of Object.entries(GROUPS)) for (const a of members) groupOf[a] = g;
for (const a of ANIMALS) if (!groupOf[a]) throw new Error(`Animal without group: ${a}`);

const errors = [];
const parseCell = (raw, where) => {
  const m = /^(\w+)\s+(.*)$/.exec(raw.trim());
  if (!m || !STATUS[m[1]]) { errors.push(`${where}: bad status in "${raw}"`); return null; }
  let [, code, rest] = m;
  const low = /\s\?$/.test(rest);
  if (low) rest = rest.replace(/\s\?$/, '');
  if (rest.startsWith('@')) {
    const key = rest.slice(1);
    if (!R[key]) { errors.push(`${where}: unknown reason @${key}`); return null; }
    rest = R[key];
  }
  const tag = /\[([A-Z,]+)\]\s*$/.exec(rest);
  if (!tag) { errors.push(`${where}: reason has no [SOURCE] tag: "${rest}"`); return null; }
  const sources = tag[1].split(',');
  for (const s of sources) if (!SOURCES[s]) errors.push(`${where}: unknown source ${s}`);
  return { code, status: STATUS[code], reason: rest.slice(0, tag.index).trim(), sources, low };
};

const pick = (obj, animal) => obj?.[animal] ?? obj?.[groupOf[animal]] ?? obj?.all;
const validKeys = new Set([...ANIMALS, ...Object.keys(GROUPS), 'all']);

// Previous app data, for the diff.
const src = fs.readFileSync(csvPath, 'utf8');
const prev = Papa.parse(src.slice(src.indexOf('`') + 1, src.lastIndexOf('`')), { header: true, skipEmptyLines: true }).data;
const prevByKey = new Map(prev.map((r) => [`${r['Category/Source']}|${r.Item}`, r]));

const seen = new Set();
const rows = foods.map((f) => {
  const key = `${f.category}|${f.item}`;
  if (seen.has(key)) errors.push(`duplicate food ${key}`);
  seen.add(key);
  for (const k of [...Object.keys(f.spec), ...Object.keys(f.base)]) {
    if (!validKeys.has(k)) errors.push(`${key}: unknown spec key "${k}"`);
  }
  const old = prevByKey.get(key);
  const cells = {};
  for (const a of ANIMALS) {
    const raw = pick(f.spec, a) ?? pick(f.base, a);
    if (!raw) { errors.push(`${key} × ${a}: unresolved`); continue; }
    const cell = parseCell(raw, `${key} × ${a}`);
    if (cell) cells[a] = { ...cell, old: old ? old[a]?.trim() : null };
  }
  return { type: f.type, category: f.category, item: f.item, icon: f.icon, added: !!f.added, cells };
});

if (errors.length) {
  console.error(errors.join('\n'));
  console.error(`\n${errors.length} error(s)`);
  process.exit(1);
}

const removed = prev
  .filter((r) => !seen.has(`${r['Category/Source']}|${r.Item}`))
  .map((r) => `${r.Type} / ${r['Category/Source']} / ${r.Item}`);

// Severity of a change: "dangerous" = app said allowed/small, now not allowed.
const base = (s) => (s == null ? null : s.startsWith('not') ? 'N' : s.startsWith('acceptable') ? 'S' : 'Y');
const stats = { cells: 0, changed: 0, dangerousFixed: 0, loosened: 0, low: 0 };
for (const r of rows) for (const c of Object.values(r.cells)) {
  stats.cells++;
  if (c.low) stats.low++;
  if (c.old == null) continue;
  if (c.old !== c.status) stats.changed++;
  if (base(c.old) !== 'N' && base(c.status) === 'N') stats.dangerousFixed++;
  if (base(c.old) === 'N' && base(c.status) !== 'N') stats.loosened++;
}

const outDir = path.join(here, 'out');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  path.join(outDir, 'review.json'),
  JSON.stringify({ generated: new Date().toISOString(), animals: ANIMALS, sources: SOURCES, stats, removed, rows }),
);
console.log(`${rows.length} foods × ${ANIMALS.length} animals`, stats);
if (removed.length) console.log('Removed:', removed.join('; '));

if (process.argv.includes('--write')) {
  const header = ['Type', 'Category/Source', 'Item', 'Icon', ...ANIMALS].join(',');
  const lines = rows.map((r) => [r.type, r.category, r.item, r.icon, ...ANIMALS.map((a) => r.cells[a].status)]
    .map((v) => (/[",]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)).join(','));
  fs.writeFileSync(csvPath,
    '// Generated by scripts/food-data/build.mjs from scripts/food-data/foods.mjs. Do not edit by hand.\n' +
    `export const csvData = \`${header}\n${lines.join('\n')}\n\`;\n`);
  console.log(`Wrote ${path.relative(root, csvPath)}`);
}
