// Shared vocabulary for the food-safety table: animals, groups, status codes,
// sources and reasons reused across many foods. See foods.mjs for the table.

export const ANIMALS = [
  'Dog', 'Cat', 'Rabbit', 'Guinea Pig', 'Hamster', 'Gerbil', 'Ferret', 'Mouse', 'Rat',
  'Chinchilla', 'Hedgehog', 'Sugar Glider', 'Parakeet', 'Cockatiel', 'Parrot', 'Lovebird',
  'Canary', 'Finch', 'Dove', 'Turtle', 'Tortoise', 'Bearded Dragon', 'Leopard Gecko',
  'Iguana', 'Snake', 'Frog', 'Toad', 'Axolotl', 'Newt', 'Salamander', 'Goldfish',
  'Betta Fish', 'Angelfish',
];

// Spec keys may name a group or a single animal. A single animal wins over its group.
export const GROUPS = {
  dog: ['Dog'],
  cat: ['Cat'],
  ferret: ['Ferret'],
  herb: ['Rabbit', 'Guinea Pig', 'Chinchilla'],
  rodent: ['Hamster', 'Gerbil', 'Mouse', 'Rat'],
  hog: ['Hedgehog'],
  glider: ['Sugar Glider'],
  psitt: ['Parakeet', 'Cockatiel', 'Parrot', 'Lovebird'],
  sbird: ['Canary', 'Finch', 'Dove'],
  turtle: ['Turtle'],
  tort: ['Tortoise'],
  dragon: ['Bearded Dragon'],
  gecko: ['Leopard Gecko'],
  iguana: ['Iguana'],
  snake: ['Snake'],
  amph: ['Frog', 'Toad', 'Axolotl', 'Newt', 'Salamander'],
  fish: ['Goldfish', 'Betta Fish', 'Angelfish'],
};

export const STATUS = {
  Y: 'allowed',
  Yc: 'allowed (cooked)',
  Yb: 'allowed (boiled)',
  Yp: 'allowed (without seeds/pits)',
  S: 'acceptable in small quantities',
  Sc: 'acceptable in small quantities (cooked)',
  Sb: 'acceptable in small quantities (boiled)',
  Sr: 'acceptable in small quantities (ripe only)',
  Sp: 'acceptable in small quantities (without seeds/pits)',
  N: 'not allowed',
};

export const SOURCES = {
  ASPCA: 'ASPCA Animal Poison Control Center – "People Foods to Avoid Feeding Your Pets" and toxic plant database',
  MSD: 'MSD (Merck) Veterinary Manual – toxicology and nutrition chapters for companion and exotic animals',
  FDA: 'U.S. FDA Center for Veterinary Medicine – consumer warnings on bone treats and xylitol',
  HRS: 'House Rabbit Society – suggested vegetables and fruits for a rabbit diet',
  RWAF: 'Rabbit Welfare Association & Fund – rabbit diet guidance',
  RSPCA: 'RSPCA / PDSA pet care guides (guinea pigs, hamsters, gerbils, rats, mice, fish)',
  VCA: 'VCA Animal Hospitals client handouts – feeding ferrets, hedgehogs, sugar gliders, chinchillas, pet birds, reptiles, amphibians, fish',
  LAF: 'Lafeber / Association of Avian Veterinarians – companion bird nutrition',
  TT: 'The Tortoise Table – plant database for tortoises',
};

// Reasons reused by many foods. Text ends with source tags in [..].
export const R = {
  allium: 'Thiosulfates/disulfides (raw, cooked or powdered) destroy red blood cells → Heinz-body anemia. [ASPCA,MSD]',
  alliumCold: 'Alliums are irritant and potentially toxic; never part of this animal\'s diet. [MSD]',
  ferretPlant: 'Obligate carnivore with a very short gut: cannot digest plant fiber or sugar; blockage and insulinoma risk. [VCA,MSD]',
  ferretCarb: 'Obligate carnivore: carbohydrates/sugars are not digested well and are linked to insulinoma. [VCA,MSD]',
  snake: 'Snakes eat only whole prey (e.g., frozen-thawed rodents); human foods are unsuitable and meat cuts cause deficiencies. [VCA,MSD]',
  gecko: 'Strict insectivore: eats only live insects and cannot digest plant matter or human foods. [VCA]',
  amph: 'Eats live invertebrates (insects, worms); human foods are unsuitable and foul the enclosure. [VCA,MSD]',
  axolotlNo: 'Carnivore fed worms, pellets and frozen foods; this human food is unsuitable. [VCA]',
  fishNo: 'Not part of this fish\'s diet; leftovers foul the water. [RSPCA,VCA]',
  betta: 'Bettas are carnivores (insect larvae, small crustaceans); plant foods are not needed. [VCA]',
  herbMeat: 'Strict herbivore: cannot digest animal protein or fat. [HRS,MSD]',
  herbStarch: 'Starchy/high-calorie food upsets the hindgut flora of herbivores (GI stasis, enterotoxemia). [HRS,MSD]',
  herbLegume: 'Dried legumes are starchy, protein-dense and contain lectins; cause gas and GI upset in herbivores. [HRS,MSD]',
  herbDairy: 'Herbivore: lactose and animal fat cause severe GI upset. [HRS,MSD]',
  herbNut: 'Very high fat; inappropriate for a fiber-based herbivore diet. [HRS,MSD]',
  tortFruit: 'Most pet tortoises (Mediterranean, Russian, sulcata) are grazers; fruit sugar disrupts gut flora. Tropical species (red-foot) differ – ask a reptile vet. [TT,VCA]',
  tortVeg: 'Grazing tortoises do best on weeds and leaves; feed this only occasionally. [TT]',
  tortStarch: 'Starchy/sugary vegetables are not appropriate for grazing tortoises. [TT]',
  tortProtein: 'High-protein legumes cause abnormal shell growth (pyramiding) and kidney strain. [TT,VCA]',
  reptMeat: 'Herbivore: animal protein causes kidney disease (gout). [VCA,MSD]',
  dragonMeat: 'Gets protein from live insects; human meats are fatty and unsuitable. [VCA]',
  reptDairy: 'Reptiles cannot digest lactose; dairy causes diarrhea. [VCA]',
  reptGrain: 'Grains and bread are not part of a reptile diet. [VCA]',
  reptNut: 'Nuts and seeds are too fatty and a choking/impaction risk for reptiles. [VCA]',
  chinFresh: 'Chinchillas need a dry, high-fiber diet; fresh produce causes bloat and diarrhea. [MSD,VCA]',
  chinSugar: 'Chinchillas are very sensitive to sugar and moisture; fruit causes bloat, diarrhea and dental problems. [MSD,VCA]',
  seedbirdMeat: 'Seed-eating bird; protein should come from egg food or insects, not meat. [VCA]',
  catVeg: 'Obligate carnivore: plain vegetable only as an occasional treat. [VCA,ASPCA]',
  catFruit: 'Obligate carnivore: plain fruit only as an occasional tiny treat. [VCA,ASPCA]',
  catNoNeed: 'Obligate carnivore: no nutritional benefit and likely GI upset. [VCA]',
  oxalateCat: 'High oxalate; cats are prone to calcium-oxalate urinary stones. [VCA]',
  oxalate: 'High oxalate binds calcium; feed only occasionally. [HRS,VCA]',
  oxalateReptile: 'High oxalate binds calcium → metabolic bone disease risk; occasional only. [VCA]',
  oxalateGlider: 'Oxalates bind calcium; sugar gliders are prone to hypocalcemia. [VCA]',
  goitrogen: 'Brassica: goitrogenic and gassy; rotate with other greens. [VCA,TT]',
  stagingCalcium: 'Good calcium-to-phosphorus ratio; a staple green. [VCA]',
  sugar: 'Sugary: occasional treat only. [VCA]',
  sugarHerb: 'High sugar: occasional treat only (about a teaspoon per kg). [HRS,RSPCA]',
  fruitSeeds: 'Seeds/pits contain cyanogenic glycosides (amygdalin); remove them and the core. [ASPCA]',
  pitHazard: 'Pit contains amygdalin and is a choking/obstruction hazard; flesh only. [ASPCA]',
  citrusCat: 'Citrus oils/psoralens irritate cats; avoid. [ASPCA]',
  citrusAcid: 'Very acidic; causes mouth sores and GI upset. [RSPCA,VCA]',
  citrusRat: 'd-Limonene in citrus causes kidney damage in male rats; avoid for all rats. [RSPCA]',
  avocadoBird: 'Persin is highly toxic to birds: heart damage, respiratory distress and death within hours. [ASPCA,MSD]',
  avocadoMammal: 'Persin is toxic to rabbits, rodents and many small mammals; very high fat. [ASPCA,MSD]',
  avocadoDog: 'Persin plus very high fat (pancreatitis); pit causes obstruction. [ASPCA]',
  avocadoRept: 'Persin is toxic to reptiles and fish too; never feed. [MSD]',
  grapeDog: 'Grapes/raisins cause acute kidney failure (tartaric acid); no safe dose. [ASPCA,MSD]',
  hogGrape: 'Hedgehog guides advise avoiding grapes/raisins because of suspected kidney toxicity. [VCA]',
  rhubarb: 'Soluble oxalates → low calcium and kidney failure. [ASPCA,MSD]',
  wildMushroom: 'Many wild mushrooms contain amatoxins and other lethal toxins and are hard to identify. [ASPCA,MSD]',
  mushroom: 'Not part of this animal\'s diet; some mushrooms irritate the GI tract. [LAF,VCA]',
  solanine: 'Nightshade: leaves, stems and unripe/green parts contain solanine. [ASPCA,MSD]',
  starfruit: 'Soluble oxalates (kidney failure) and the neurotoxin caramboxin. [ASPCA,MSD]',
  elderberry: 'Stems, leaves, seeds and unripe/raw berries contain cyanogenic glycosides. [MSD]',
  bones: 'Cooked bones splinter; any bone can break teeth, choke, obstruct or perforate the gut. [FDA,ASPCA]',
  fatTrim: 'Fat trimmings/fatty skin → vomiting and pancreatitis. [ASPCA,MSD]',
  cookedMeat: 'Plain, cooked, unseasoned, no bones; raw meat carries Salmonella/Listeria. [ASPCA,FDA]',
  cookedPork: 'Cook thoroughly: raw pork can carry Trichinella and Aujeszky\'s disease (fatal to dogs/cats). [MSD]',
  liverDog: 'Very rich in vitamin A; small amounts, cooked – excess causes hypervitaminosis A. [MSD]',
  organ: 'Nutritious but rich; cooked, small portions as part of a varied diet. [MSD]',
  smallOmniMeat: 'Plain cooked lean poultry/fish is a good occasional protein treat; skip fatty or unusual cuts. [RSPCA,VCA]',
  smallOmniRich: 'Too fatty or unusual for small omnivores; use plain cooked lean poultry instead. [RSPCA,VCA]',
  birdMeat: 'Small bits of plain cooked lean meat are an occasional protein treat for parrots. [LAF]',
  birdRich: 'Fatty/organ meats are inappropriate for companion birds (fat, iron storage disease). [LAF]',
  chocolate: 'Theobromine and caffeine: vomiting, arrhythmia, seizures, death. [ASPCA,MSD]',
  caffeine: 'Methylxanthines (caffeine): restlessness, arrhythmia, seizures, death. [ASPCA,MSD]',
  alcohol: 'Ethanol causes vomiting, hypoglycemia, CNS depression and death in small animals. [ASPCA,MSD]',
  xylitol: 'Xylitol causes a sudden insulin surge (hypoglycemia) and liver failure in dogs; unsafe for all pets. [FDA,ASPCA]',
  macadamia: 'Weakness, tremors, hyperthermia in dogs; mechanism unknown. [ASPCA,MSD]',
  nutDog: 'High fat (pancreatitis), choking/obstruction risk; molds can be tremorgenic. [ASPCA]',
  nutCat: 'High fat, no benefit for an obligate carnivore; GI upset. [ASPCA]',
  lactose: 'Most adults of this species are lactose intolerant → diarrhea. [ASPCA,VCA]',
  dairyFat: 'High fat (and sugar) → GI upset and pancreatitis risk. [ASPCA]',
  dairyOk: 'Plain, low-lactose dairy is tolerated in small amounts; watch for diarrhea. [ASPCA,VCA]',
  hogDairy: 'Hedgehogs are lactose intolerant; only a little plain yogurt is commonly tolerated. [VCA]',
  birdDairy: 'Birds lack lactase; only small amounts of low-lactose dairy (plain yogurt, hard cheese). [LAF]',
  fishDairy: 'Fish cannot digest dairy; fouls the water. [VCA]',
  grainDog: 'Plain cooked grain is fine in moderation. [VCA]',
  grainRodent: 'Plain grains are a natural part of rodent and bird diets. [RSPCA,LAF]',
  bread: 'Low nutrition, salty and filling; small occasional amounts only. [RSPCA,LAF]',
  breadFish: 'Bread swells, causes bloating and fouls the water. [RSPCA]',
  seedTreat: 'Fatty seed: treat, not a staple (obesity, fatty liver). [LAF,RSPCA]',
};
